# From https://github.com/nezhahq/agent/blob/main/.github/workflows/test.yml

name: Run Tests

on:
  push:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/test.yml"
  pull_request:
    branches:
      - master

jobs:
  tests:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu, windows, macos]

    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - name: Unit test
        run: |
          go test -v ./...

      - name: Build test
        run: go build -v ./cmd/torrentremover
